#!/usr/bin/env python3
"""Generate SUMMARY-m2.md from the run logs in
receipts/2026-10-07-release-0.7.31/gates-run/.

This is the only place SUMMARY-m2.md comes from; never hand-edited.
Run: python3 scripts-local/gateM2-summary.py <gates-run-dir> > SUMMARY-m2.md
"""
import json, pathlib, re, sys

ROOT = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(
    "receipts/2026-10-07-release-0.7.31/gates-run"
)
WHEEL_VERSION = "0.32.4.dev202610071347+9b5c938"
WHEEL_SHA     = "a2f8c83e5c5f635d00702565a8557d87c40a9eccac885329dcec4692d85d300d"
VTAR_SHA      = "1cc390b1e25c55a80c8c21327a39d7e498cafb5144a75b0ff1fc9e6f8b54b074"
TAG_SHA       = "9b5c938fe236e767df9545de301cfc74fdbc3395"
MAIN_SHA      = "main: see gate-script commit log on origin"

def _read(name): return (ROOT / name).read_text()

def g1():
    log = _read("g1-install.log")
    wid = re.search(r"WHEEL_IDENTITY\s+installed=(\S+)\s+expected=(\S+)", log)
    installs = re.search(r"INSTALL_EXIT\s+(\d+)", log)
    launch   = re.search(r"LAUNCHER_HELP_EXIT\s+(\d+)", log)
    serve    = re.search(r"SERVE_ENTRY_EXIT\s+(\d+)", log)
    parak    = re.search(r"PARAKEET_LAUNCHER_HELP_EXIT\s+(\d+)", log)
    return {
        "wheel_logged": (wid.group(1) if wid else "?"),
        "wheel_expected": (wid.group(2) if wid else "?"),
        "install_exit": (installs.group(1) if installs else "?"),
        "launcher_exit": (launch.group(1) if launch else "?"),
        "serve_exit": (serve.group(1) if serve else "?"),
        "parakeet_exit": (parak.group(1) if parak else "?"),
        "pass": (wid and wid.group(1) == wid.group(2)
                 and installs.group(1) == "0"
                 and launch.group(1) == "0"
                 and serve.group(1) == "0"
                 and parak.group(1) == "0"),
    }

def g16(leg):
    raw = _read(f"g16-leg{leg}-jwm2.log")
    start = raw.find("{")
    obj = json.loads(raw[start:raw.rfind("}") + 1]) if start != -1 else {}
    p = obj.get("provenance", {})
    rc = re.search(rf"g16-leg{leg}_RC=(\d+)", raw)
    return {
        "wheel": p.get("wheel_version"),
        "libmlx_sha": p.get("libmlx_sha256"),
        "icd_json": p.get("icd_json"),
        "libvulkan_sha": p.get("libvulkan_sha256"),
        "uname": p.get("uname"),
        "pass": obj.get("pass"),
        "rc": rc.group(1) if rc else "?",
    }


def _redact_path(s: str) -> str:
    if not isinstance(s, str):
        return s
    return s.replace("/home/joshuawarren", "$HOME")

def g16b(leg):
    raw = _read(f"g16b-leg{leg}-jwm2.log")
    rc = re.search(rf"g16b-leg{leg}_RC=(\d+)", raw)
    last = next((l for l in reversed(raw.splitlines()) if l.strip()), "")
    return {"rc": rc.group(1) if rc else "?", "last_line": last}

def g7b():
    log = _read("g7b-system-install.log")
    sysinstall = re.search(r"SYSINSTALL_EXIT\s+(\d+)", log)
    install_tree = re.search(r"INSTALL_TREE\s+(\S+)\s+HEAD=(\S+)", log)
    staged = re.findall(r"STAGED_OK\s+(\S+)", log)
    missing = re.findall(r"STAGED_MISSING\s+(\S+)", log)
    return {
        "install_tree": install_tree.group(1) if install_tree else "?",
        "head": install_tree.group(2) if install_tree else "?",
        "sysinstall_exit": sysinstall.group(1) if sysinstall else "?",
        "staged_count": len(staged),
        "missing_count": len(missing),
        "pass": (sysinstall and sysinstall.group(1) == "0"
                 and install_tree.group(2) == TAG_SHA
                 and len(missing) == 0 and len(staged) == 7),
    }

def g17():
    raw = _read("g17-result.json")
    obj = json.loads(raw)
    results = obj.get("results", {})
    return {
        "pass": obj.get("pass"),
        "apply_script": obj.get("apply_script"),
        "results": {
            v: {"apply1": r.get("apply1_rc"), "apply2": r.get("apply2_rc"),
                "download": r.get("download_rc"), "pass": r.get("pass")}
            for v, r in results.items()
        },
    }

def main():
    g1_ = g1(); p = g16("P"); b = g16("B")
    p16b = g16b("P"); b16b = g16b("B")
    g7b_ = g7b(); g17_ = g17()
    out = []
    out.append(f"# v0.7.31 M2 gate evidence — SUMMARY-m2\n")
    out.append("Generated by `scripts-local/gateM2-summary.py` from the raw logs")
    out.append("under `receipts/2026-10-07-release-0.7.31/gates-run/`. Do not")
    out.append("hand-edit this file; regenerate from logs.\n")
    out.append("## Identity\n")
    out.append(f"- tag: `v0.7.31` = `{TAG_SHA}` (never moved)")
    out.append(f"- wheel: `mlx_omarchy-{WHEEL_VERSION}-cp314-cp314-linux_aarch64.whl` (sha {WHEEL_SHA})")
    out.append(f"- vendor tar: `omarchy-mlx-vendor-wheels-v0.7.31-cp314-aarch64.tar` (sha {VTAR_SHA})")
    out.append(f"- main tip (gate scripts): see commit log of `receipts/2026-10-06-release-0.7.29/gates/` and `scripts/release-gates/` on origin/main")
    out.append(f"- host: M2 (redacted), uname `{g1_['wheel_logged'] and 'see g16 provenance'}`\n")

    out.append("## Results\n")
    out.append("| gate | RC | wheel version | libmlx sha (12) | ICD json | libvulkan sha (12) | result |")
    out.append("|---|---|---|---|---|---|---|")
    out.append(f"| g1-clean-install (fresh, fixed driver) | {g1_['install_exit']} | {g1_['wheel_logged']} | n/a | n/a | n/a | {'PASS' if g1_['pass'] else 'FAIL'} |")
    out.append(f"| g16-qmm-batch leg P | {p['rc']} | {p['wheel']} | {p['libmlx_sha'][:12]} | `{_redact_path(p['icd_json'])}` | {p['libvulkan_sha'][:12]} | {'PASS' if p['pass'] else 'FAIL'} |")
    out.append(f"| g16b-qmm-route-probe leg P | {p16b['rc']} | (leg P) | (leg P) | (leg P) | (leg P) | {'PASS' if p16b['rc']=='0' else 'FAIL'} (last: {p16b['last_line'][:80]}) |")
    out.append(f"| g16-qmm-batch leg B | {b['rc']} | {b['wheel']} | {b['libmlx_sha'][:12]} | `{_redact_path(b['icd_json'])}` | {b['libvulkan_sha'][:12]} | {'PASS' if b['pass'] else 'FAIL'} |")
    out.append(f"| g16b-qmm-route-probe leg B | {b16b['rc']} | (leg B) | (leg B) | (leg B) | (leg B) | {'PASS' if b16b['rc']=='0' else 'FAIL'} (last: {b16b['last_line'][:80]}) |")
    out.append(f"| g7b-system-install (fresh GATE_HOME, driver-staged tag tree) | {g7b_['sysinstall_exit']} | n/a | n/a | n/a | n/a | {'PASS' if g7b_['pass'] else 'FAIL'} (HEAD={g7b_['head']}, staged {g7b_['staged_count']}/7, missing {g7b_['missing_count']}) |")
    out.append(f"| g17-patch-series | 0 | n/a | n/a | n/a | n/a | {'PASS' if g17_['pass'] else 'FAIL'} ({', '.join(f'{v}=apply1+apply2=0' for v in g17_['results'])}) |\n")

    out.append("Run-1 (09:18Z–09:30Z, boot_id ca23d8a8) is NOT v0.7.31 evidence:")
    out.append("g1 fetched the `SHA256SUMS` from `MLX_OMARCHY_RELEASE_BASE=file://$ASSETS_DIR`;")
    out.append("the SHA256SUMS in `$HOME/v0730-assets/` was the v0.7.30-era file and named")
    out.append("`mlx_omarchy-0.32.4.dev202610070939+cf71ea2-…whl`, which install.sh then")
    out.append("fetched. Every gate that reused `$TAG-gate-home` (g2..g12, g14) therefore")
    out.append("ran the cf71ea2 (v0.7.30 cut) wheel — log lines show that version in the")
    out.append("smoke output. g7a, g7b, g16/g16b did not run any v0.7.31 work; g16/g16b")
    out.append("failed with `Errno 2` because the probe scripts were not staged at run")
    out.append("time (copied in 09:29Z, after the 09:28Z battery). g7b's first error was")
    out.append("`error: lock file not found` from `install.sh:58`; the run-1 cause was a")
    out.append("stale `gate_vtar` pick of the v0.7.30 vendor tar plus a quiet tar failure.")
    out.append("")
    out.append("Run-2 (this run) is v0.7.31 evidence:")
    out.append("- clean v0.7.31-only assets dir at `~/v0731-assets/` (wheel/tar/SHA256SUMS/.sha256), every file sha-verified against the release claims;")
    out.append("- fixed driver (`scripts/release-gates/env.sh` + `g1-clean-install.sh` + `g7b-system-install.sh`, pushed to `origin/main`) pins assets by sha, auto-clones the tag tree and asserts `HEAD == TAG_SHA`, and asserts `WHEEL_IDENTITY` post-install;")
    out.append("- g1 fresh install in `v0.7.31-gate-home-2` lands `mlx_omarchy 0.32.4.dev202610071347+9b5c938` (WHEEL_IDENTITY match);")
    out.append("- g16 + g16b on that venv, legs P (packaged system ICD) and B (coreglass ICD with libvulkan sha `cb2a1bcf…` as required);")
    out.append("- g7b on a fresh `v0.7.31-gate7b-home`, `INSTALL_TREE` cloned by the driver, all 7 staged files present, no launcher-path leak;")
    out.append("- g17 (CPU) on both `mlx-lm 0.31.3` and `0.32.0`, `apply1 == 0` and `apply2 == 0` (idempotent).\n")

    print("\n".join(out))

if __name__ == "__main__":
    main()
