#!/usr/bin/env python3
"""Generate SUMMARY-m2-12.2.md from the aurora-12.2 logs in
receipts/2026-10-07-release-0.7.31/gates-run/m2-aurora-12.2/.

Script-generated only; never hand-edit. Handles the partial set: gates
without logs print NOT RUN (post-hard-end), sourced from gates.done.
Run: python3 scripts-local/gateM2-summary-122.py <dir> > SUMMARY-m2-12.2.md
"""
import json, pathlib, re, sys

ROOT = pathlib.Path(sys.argv[1])
WHEEL = "0.32.4.dev202610071347+9b5c938"
TAG_SHA = "9b5c938fe236e767df9545de301cfc74fdbc3395"
UNAME = "7.1.12-2-12.2-sep-ARCH"
ALL_GATES = ["g1-clean-install", "g17-patch-series", "g16-legP", "g16b-legP",
             "g16-legB", "g16b-legB", "g7b-system-install", "g2-online-9b",
             "g3-online-4b-card", "g4-offline", "g5-laya", "g6-codec",
             "g7a-packaged-icd", "g8-kokoro", "g9-speak-queue",
             "g11-card-9b", "g14-routing", "g12-kokoro-stream",
             "g10-kokoro-primer"]

def read(name):
    p = ROOT / name
    return p.read_text() if p.exists() else ""

def main():
    done_raw = read("gates.done")
    pairs = re.findall(r"(\S+?)_RC=(\d+) wall=(\d+)s", done_raw)
    done = {g: (rc, wall) for g, rc, wall in pairs}
    lines = []
    lines.append("# v0.7.31 M2 gate evidence — SUMMARY-m2-12.2 (aurora 12.2)\n")
    lines.append("Generated by `scripts-local/gateM2-summary-122.py` from the raw")
    lines.append("logs under `receipts/2026-10-07-release-0.7.31/gates-run/m2-aurora-12.2/`.")
    lines.append("Do not hand-edit; regenerate from logs.\n")
    lines.append(f"- kernel: `{UNAME}` (boot_id in every log header)")
    lines.append(f"- tag: `v0.7.31` = `{TAG_SHA}` (never moved)")
    lines.append(f"- wheel: `{WHEEL}` (sha a2f8c83e5c5f635d00702565a8557d87c40a9eccac885329dcec4692d85d300d)")
    lines.append("- GATE_HOME fresh (`v0.7.31-gate-home-3`); g7b on a fresh `v0.7.31-gate7b-home-12.2`")
    lines.append("- GPU gates ran inside `gpu-turn` tickets (≤15 min); CPU-only gates")
    lines.append("  (g7b, g17) ran outside the lock; the 15:50Z hard end killed the g2")
    lines.append("  download mid-ticket, so g2/g3 and the gates behind them are NOT RUN\n")
    lines.append("## Results\n")
    lines.append("| gate | RC | wall | wheel version | ICD / libvulkan | result |")
    lines.append("|---|---|---|---|---|---|")
    for g in ALL_GATES:
        if g in done:
            rc, wall = done[g]
            extra = ""
            if g == "g1-clean-install":
                m = re.search(r"WHEEL_IDENTITY installed=(\S+) expected=(\S+)", read("g1-install.log"))
                extra = f"{m.group(1)}" if m else "?"
            elif g.startswith("g16"):
                leg = "P" if "legP" in g else "B"
                raw = read(f"g16-leg{leg}-jwm2.log") if g.startswith("g16-") else read(f"g16b-leg{leg}-jwm2.log")
                start = raw.find("{")
                if start != -1:
                    p = json.loads(raw[start:raw.rfind("}") + 1]).get("provenance", {})
                    extra = f"{p.get('wheel_version','?')} | {p.get('icd_json','?')} libvulkan {str(p.get('libvulkan_sha256','?'))[:12]}"
                    result = "PASS" if '"pass": true' in raw else "FAIL"
                else:
                    result = "PASS" if rc == "0" else "FAIL"
                lines.append(f"| {g} | {rc} | {wall}s | {extra} | n/a | {result} |")
                continue
            elif g == "g17-patch-series":
                raw = read("g17-result.json")
                extra = "both mlx-lm lines apply1+apply2 rc=0" if '"pass": true' in raw else "FAIL"
            elif g == "g7b-system-install":
                raw = read("g7b-system-install.log")
                ok = "SYSINSTALL_EXIT 0" in raw and "STAGED_MISSING" not in raw and "GATE7B_EXIT 0" in raw
                extra = f"HEAD={TAG_SHA[:12]}, 7/7 staged" if ok else "FAIL"
            result = "PASS" if rc == "0" else f"FAIL(RC={rc})"
            lines.append(f"| {g} | {rc} | {wall}s | {extra} | n/a | {result} |")
        else:
            lines.append(f"| {g} | — | — | — | — | NOT RUN (hard end 15:50Z; runs after the GLM session) |")
    lines.append("")
    print("\n".join(lines))

if __name__ == "__main__":
    main()
